// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZCDDWQ1UGNK64GFxxXODeW3Jf1aW1qHQ',
    appId: '1:329380333899:web:5f1299cb858c83954b40ce',
    messagingSenderId: '329380333899',
    projectId: 'focusnflow-zach-gsu',
    authDomain: 'focusnflow-zach-gsu.firebaseapp.com',
    storageBucket: 'focusnflow-zach-gsu.firebasestorage.app',
    measurementId: 'G-X1W46X1B9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa0cEQ31n9sx63pwusul9Uha-tnBJruO4',
    appId: '1:329380333899:android:0951d627e9575c0f4b40ce',
    messagingSenderId: '329380333899',
    projectId: 'focusnflow-zach-gsu',
    storageBucket: 'focusnflow-zach-gsu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC320H-4siZdLIKqd_yNkJCkHCwxgGEO5E',
    appId: '1:329380333899:ios:81abecd17213fb2b4b40ce',
    messagingSenderId: '329380333899',
    projectId: 'focusnflow-zach-gsu',
    storageBucket: 'focusnflow-zach-gsu.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC320H-4siZdLIKqd_yNkJCkHCwxgGEO5E',
    appId: '1:329380333899:ios:81abecd17213fb2b4b40ce',
    messagingSenderId: '329380333899',
    projectId: 'focusnflow-zach-gsu',
    storageBucket: 'focusnflow-zach-gsu.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZCDDWQ1UGNK64GFxxXODeW3Jf1aW1qHQ',
    appId: '1:329380333899:web:88e7ab7d77c1252d4b40ce',
    messagingSenderId: '329380333899',
    projectId: 'focusnflow-zach-gsu',
    authDomain: 'focusnflow-zach-gsu.firebaseapp.com',
    storageBucket: 'focusnflow-zach-gsu.firebasestorage.app',
    measurementId: 'G-VFLRBJ1VYZ',
  );

}